package com.echo.dataobject;

import java.io.Serializable;
import java.util.Date;

public class AreaDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.area_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_area.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date lastEditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_id
     *
     * @return the value of tb_area.area_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_id
     *
     * @param areaId the value for tb_area.area_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.area_name
     *
     * @return the value of tb_area.area_name
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.area_name
     *
     * @param areaName the value for tb_area.area_name
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.priority
     *
     * @return the value of tb_area.priority
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.priority
     *
     * @param priority the value for tb_area.priority
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.create_time
     *
     * @return the value of tb_area.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.create_time
     *
     * @param createTime the value for tb_area.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_area.last_edit_time
     *
     * @return the value of tb_area.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_area.last_edit_time
     *
     * @param lastEditTime the value for tb_area.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    @Override
    public String toString() {
        return "AreaDO{" +
                "areaId=" + areaId +
                ", areaName='" + areaName + '\'' +
                ", priority=" + priority +
                ", createTime=" + createTime +
                ", lastEditTime=" + lastEditTime +
                '}';
    }
}