package com.echo.dataobject;

import java.util.Date;

public class AwardDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_id
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private Integer awardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_name
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private String awardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_desc
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private String awardDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.award_img
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private String awardImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.point
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.priority
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.create_time
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.expire_time
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.last_edit_time
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.enable_status
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_award.shop_id
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */

    //属于那个店铺
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_id
     *
     * @return the value of tb_award.award_id
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getAwardId() {
        return awardId;
    }

    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_id
     *
     * @param awardId the value for tb_award.award_id
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_name
     *
     * @return the value of tb_award.award_name
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public String getAwardName() {
        return awardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_name
     *
     * @param awardName the value for tb_award.award_name
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setAwardName(String awardName) {
        this.awardName = awardName == null ? null : awardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_desc
     *
     * @return the value of tb_award.award_desc
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public String getAwardDesc() {
        return awardDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_desc
     *
     * @param awardDesc the value for tb_award.award_desc
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setAwardDesc(String awardDesc) {
        this.awardDesc = awardDesc == null ? null : awardDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.award_img
     *
     * @return the value of tb_award.award_img
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public String getAwardImg() {
        return awardImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.award_img
     *
     * @param awardImg the value for tb_award.award_img
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setAwardImg(String awardImg) {
        this.awardImg = awardImg == null ? null : awardImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.point
     *
     * @return the value of tb_award.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.point
     *
     * @param point the value for tb_award.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.priority
     *
     * @return the value of tb_award.priority
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.priority
     *
     * @param priority the value for tb_award.priority
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.create_time
     *
     * @return the value of tb_award.create_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.create_time
     *
     * @param createTime the value for tb_award.create_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.last_edit_time
     *
     * @return the value of tb_award.last_edit_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.last_edit_time
     *
     * @param lastEditTime the value for tb_award.last_edit_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.enable_status
     *
     * @return the value of tb_award.enable_status
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.enable_status
     *
     * @param enableStatus the value for tb_award.enable_status
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_award.shop_id
     *
     * @return the value of tb_award.shop_id
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_award.shop_id
     *
     * @param shopId the value for tb_award.shop_id
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    @Override
    public String toString() {
        return "AwardDO{" +
                "awardId=" + awardId +
                ", awardName='" + awardName + '\'' +
                ", awardDesc='" + awardDesc + '\'' +
                ", awardImg='" + awardImg + '\'' +
                ", point=" + point +
                ", priority=" + priority +
                ", createTime=" + createTime +
                ", lastEditTime=" + lastEditTime +
                ", enableStatus=" + enableStatus +
                ", shopId=" + shopId +
                '}';
    }
}