package com.echo.dataobject;

import java.io.Serializable;
import java.util.Date;

public class HeadLineDO  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.line_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.line_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.line_link
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String lineLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.line_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String lineImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.enable_status
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer enableStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_headline.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date lastEditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.line_id
     *
     * @return the value of tb_headline.line_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.line_id
     *
     * @param lineId the value for tb_headline.line_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLineId(Integer lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.line_name
     *
     * @return the value of tb_headline.line_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.line_name
     *
     * @param lineName the value for tb_headline.line_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLineName(String lineName) {
        this.lineName = lineName == null ? null : lineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.line_link
     *
     * @return the value of tb_headline.line_link
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getLineLink() {
        return lineLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.line_link
     *
     * @param lineLink the value for tb_headline.line_link
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLineLink(String lineLink) {
        this.lineLink = lineLink == null ? null : lineLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.line_img
     *
     * @return the value of tb_headline.line_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getLineImg() {
        return lineImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.line_img
     *
     * @param lineImg the value for tb_headline.line_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLineImg(String lineImg) {
        this.lineImg = lineImg == null ? null : lineImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.priority
     *
     * @return the value of tb_headline.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.priority
     *
     * @param priority the value for tb_headline.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.enable_status
     *
     * @return the value of tb_headline.enable_status
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.enable_status
     *
     * @param enableStatus the value for tb_headline.enable_status
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.create_time
     *
     * @return the value of tb_headline.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.create_time
     *
     * @param createTime the value for tb_headline.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_headline.last_edit_time
     *
     * @return the value of tb_headline.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_headline.last_edit_time
     *
     * @param lastEditTime the value for tb_headline.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    @Override
    public String toString() {
        return "HeadLineDO{" +
                "lineId=" + lineId +
                ", lineName='" + lineName + '\'' +
                ", lineLink='" + lineLink + '\'' +
                ", lineImg='" + lineImg + '\'' +
                ", priority=" + priority +
                ", enableStatus=" + enableStatus +
                ", createTime=" + createTime +
                ", lastEditTime=" + lastEditTime +
                '}';
    }
}