package com.echo.dataobject;

import java.util.Date;

public class LocalAuthDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.local_auth_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer localAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.username
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.password
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_auth.user_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer userId;

    //与personinfo相关联
    OwnerDO personInfo;

    public OwnerDO getPersonInfo() {
        return personInfo;
    }

    public void setPersonInfo(OwnerDO personInfo) {
        this.personInfo = personInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_auth.local_auth_id
     *
     * @return the value of tb_local_auth.local_auth_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getLocalAuthId() {
        return localAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_auth.local_auth_id
     *
     * @param localAuthId the value for tb_local_auth.local_auth_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLocalAuthId(Integer localAuthId) {
        this.localAuthId = localAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_auth.username
     *
     * @return the value of tb_local_auth.username
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_auth.username
     *
     * @param username the value for tb_local_auth.username
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_auth.password
     *
     * @return the value of tb_local_auth.password
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_auth.password
     *
     * @param password the value for tb_local_auth.password
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_auth.create_time
     *
     * @return the value of tb_local_auth.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_auth.create_time
     *
     * @param createTime the value for tb_local_auth.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_auth.last_edit_time
     *
     * @return the value of tb_local_auth.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_auth.last_edit_time
     *
     * @param lastEditTime the value for tb_local_auth.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_auth.user_id
     *
     * @return the value of tb_local_auth.user_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_auth.user_id
     *
     * @param userId the value for tb_local_auth.user_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "LocalAuthDO{" +
                "localAuthId=" + localAuthId +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", createTime=" + createTime +
                ", lastEditTime=" + lastEditTime +
                ", userId=" + userId +
                ", personInfo=" + personInfo +
                '}';
    }
}