package com.echo.dataobject;

import java.util.Date;

public class ProductImgDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.product_img_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer productImgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.img_addr
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String imgAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.img_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String imgDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_img.product_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.product_img_id
     *
     * @return the value of tb_product_img.product_img_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getProductImgId() {
        return productImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.product_img_id
     *
     * @param productImgId the value for tb_product_img.product_img_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductImgId(Integer productImgId) {
        this.productImgId = productImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.img_addr
     *
     * @return the value of tb_product_img.img_addr
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.img_addr
     *
     * @param imgAddr the value for tb_product_img.img_addr
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.img_desc
     *
     * @return the value of tb_product_img.img_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getImgDesc() {
        return imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.img_desc
     *
     * @param imgDesc the value for tb_product_img.img_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc == null ? null : imgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.priority
     *
     * @return the value of tb_product_img.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.priority
     *
     * @param priority the value for tb_product_img.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.create_time
     *
     * @return the value of tb_product_img.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.create_time
     *
     * @param createTime the value for tb_product_img.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_img.product_id
     *
     * @return the value of tb_product_img.product_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_img.product_id
     *
     * @param productId the value for tb_product_img.product_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Override
    public String toString() {
        return "ProductImgDO{" +
                "productImgId=" + productImgId +
                ", imgAddr='" + imgAddr + '\'' +
                ", imgDesc='" + imgDesc + '\'' +
                ", priority=" + priority +
                ", createTime=" + createTime +
                ", productId=" + productId +
                '}';
    }
}