package com.echo.dataobject;

import java.util.Date;

public class ProductCategoryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String productCategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.product_category_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String productCategoryDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date lastEditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_category.shop_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.product_category_id
     *
     * @return the value of tb_product_category.product_category_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.product_category_id
     *
     * @param productCategoryId the value for tb_product_category.product_category_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductCategoryId(Integer productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.product_category_name
     *
     * @return the value of tb_product_category.product_category_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getProductCategoryName() {
        return productCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.product_category_name
     *
     * @param productCategoryName the value for tb_product_category.product_category_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductCategoryName(String productCategoryName) {
        this.productCategoryName = productCategoryName == null ? null : productCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.product_category_desc
     *
     * @return the value of tb_product_category.product_category_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getProductCategoryDesc() {
        return productCategoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.product_category_desc
     *
     * @param productCategoryDesc the value for tb_product_category.product_category_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductCategoryDesc(String productCategoryDesc) {
        this.productCategoryDesc = productCategoryDesc == null ? null : productCategoryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.priority
     *
     * @return the value of tb_product_category.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.priority
     *
     * @param priority the value for tb_product_category.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.create_time
     *
     * @return the value of tb_product_category.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.create_time
     *
     * @param createTime the value for tb_product_category.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.last_edit_time
     *
     * @return the value of tb_product_category.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.last_edit_time
     *
     * @param lastEditTime the value for tb_product_category.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_category.shop_id
     *
     * @return the value of tb_product_category.shop_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_category.shop_id
     *
     * @param shopId the value for tb_product_category.shop_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    @Override
    public String toString() {
        return "ProductCategoryDO{" +
                "productCategoryId=" + productCategoryId +
                ", productCategoryName='" + productCategoryName + '\'' +
                ", productCategoryDesc='" + productCategoryDesc + '\'' +
                ", priority=" + priority +
                ", createTime=" + createTime +
                ", lastEditTime=" + lastEditTime +
                ", shopId=" + shopId +
                '}';
    }
}