package com.echo.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class ProductDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.img_addr
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String imgAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.enable_status
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.point
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.product_category_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private ProductCategoryDO productCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.shop_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
//    private Integer shopId;
    private ShopDO shop;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.normal_price
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private BigDecimal normalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.promotion_price
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private BigDecimal promotionPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_id
     *
     * @return the value of tb_product.product_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.product_id
     *
     * @param productId the value for tb_product.product_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_name
     *
     * @return the value of tb_product.product_name
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.product_name
     *
     * @param productName the value for tb_product.product_name
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_desc
     *
     * @return the value of tb_product.product_desc
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.product_desc
     *
     * @param productDesc the value for tb_product.product_desc
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.img_addr
     *
     * @return the value of tb_product.img_addr
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getImgAddr() {
        return imgAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.img_addr
     *
     * @param imgAddr the value for tb_product.img_addr
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setImgAddr(String imgAddr) {
        this.imgAddr = imgAddr == null ? null : imgAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.priority
     *
     * @return the value of tb_product.priority
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.priority
     *
     * @param priority the value for tb_product.priority
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.create_time
     *
     * @return the value of tb_product.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.create_time
     *
     * @param createTime the value for tb_product.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.last_edit_time
     *
     * @return the value of tb_product.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.last_edit_time
     *
     * @param lastEditTime the value for tb_product.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.enable_status
     *
     * @return the value of tb_product.enable_status
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.enable_status
     *
     * @param enableStatus the value for tb_product.enable_status
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.point
     *
     * @return the value of tb_product.point
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.point
     *
     * @param point the value for tb_product.point
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.product_category_id
     *
     * @return the value of tb_product.product_category_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */

    public ProductCategoryDO getProductCategory() {
        return productCategory;
    }

    public void setProductCategory(ProductCategoryDO productCategory) {
        this.productCategory = productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.shop_id
     *
     * @return the value of tb_product.shop_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
//    public Integer getShopId() {
//        return shopId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.shop_id
     *
     * @param shopId the value for tb_product.shop_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
//    public void setShopId(Integer shopId) {
//        this.shopId = shopId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.normal_price
     *
     * @return the value of tb_product.normal_price
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public BigDecimal getNormalPrice() {
        return normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.normal_price
     *
     * @param normalPrice the value for tb_product.normal_price
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setNormalPrice(BigDecimal normalPrice) {
        this.normalPrice = normalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.promotion_price
     *
     * @return the value of tb_product.promotion_price
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.promotion_price
     *
     * @param promotionPrice the value for tb_product.promotion_price
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    public ShopDO getShop() {
        return shop;
    }

    public void setShop(ShopDO shop) {
        this.shop = shop;
    }

    @Override
    public String toString() {
        return "ProductDO{" +
                "productId=" + productId +
                ", productName='" + productName + '\'' +
                ", productDesc='" + productDesc + '\'' +
                ", imgAddr='" + imgAddr + '\'' +
                ", priority=" + priority +
                ", createTime=" + createTime +
                ", lastEditTime=" + lastEditTime +
                ", enableStatus=" + enableStatus +
                ", point=" + point +
                ", productCategory=" + productCategory +
                ", shop=" + shop +
                ", normalPrice=" + normalPrice +
                ", promotionPrice=" + promotionPrice +
                '}';
    }
}