package com.echo.dataobject;

import java.util.Date;

public class ShopCategoryDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer shopCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_name
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String shopCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_desc
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String shopCategoryDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.shop_category_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private String shopCategoryImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.priority
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.create_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.last_edit_time
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    private Date lastEditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_shop_category.parent_id
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    //父类的id
//    private Integer parentId;
    //父类别
    private ShopCategoryDO parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_id
     *
     * @return the value of tb_shop_category.shop_category_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getShopCategoryId() {
        return shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_id
     *
     * @param shopCategoryId the value for tb_shop_category.shop_category_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */


    public void setShopCategoryId(Integer shopCategoryId) {
        this.shopCategoryId = shopCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_name
     *
     * @return the value of tb_shop_category.shop_category_name
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getShopCategoryName() {
        return shopCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_name
     *
     * @param shopCategoryName the value for tb_shop_category.shop_category_name
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setShopCategoryName(String shopCategoryName) {
        this.shopCategoryName = shopCategoryName == null ? null : shopCategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_desc
     *
     * @return the value of tb_shop_category.shop_category_desc
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getShopCategoryDesc() {
        return shopCategoryDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_desc
     *
     * @param shopCategoryDesc the value for tb_shop_category.shop_category_desc
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setShopCategoryDesc(String shopCategoryDesc) {
        this.shopCategoryDesc = shopCategoryDesc == null ? null : shopCategoryDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.shop_category_img
     *
     * @return the value of tb_shop_category.shop_category_img
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public String getShopCategoryImg() {
        return shopCategoryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.shop_category_img
     *
     * @param shopCategoryImg the value for tb_shop_category.shop_category_img
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setShopCategoryImg(String shopCategoryImg) {
        this.shopCategoryImg = shopCategoryImg == null ? null : shopCategoryImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.priority
     *
     * @return the value of tb_shop_category.priority
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.priority
     *
     * @param priority the value for tb_shop_category.priority
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.create_time
     *
     * @return the value of tb_shop_category.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.create_time
     *
     * @param createTime the value for tb_shop_category.create_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.last_edit_time
     *
     * @return the value of tb_shop_category.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public Date getLastEditTime() {
        return lastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_shop_category.last_edit_time
     *
     * @param lastEditTime the value for tb_shop_category.last_edit_time
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    public void setLastEditTime(Date lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public ShopCategoryDO getParent() {
        return parent;
    }

    public void setParent(ShopCategoryDO parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_shop_category.parent_id
     *
     * @return the value of tb_shop_category.parent_id
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */

    @Override
    public String toString() {
        return "ShopCategoryDO{" +
                "shopCategoryId=" + shopCategoryId +
                ", shopCategoryName='" + shopCategoryName + '\'' +
                ", shopCategoryDesc='" + shopCategoryDesc + '\'' +
                ", shopCategoryImg='" + shopCategoryImg + '\'' +
                ", priority=" + priority +
                ", createTime=" + createTime +
                ", lastEditTime=" + lastEditTime +
                ", parent=" + parent +
                '}';
    }
}