package com.echo.dataobject;

import java.util.Date;

public class UserProductMapDO {
    private Integer userProductId;

    private Date createTime;

    private Integer point;

    //顾客信息
    private OwnerDO user;

    //商品信息
    private ProductDO product;
    //private Integer productId;

    //店铺信息
    private ShopDO shop;
    //private Integer shopId;

    //操作员的信息
    private OwnerDO operator;


    public Integer getUserProductId() {
        return userProductId;
    }

    public void setUserProductId(Integer userProductId) {
        this.userProductId = userProductId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.create_time
     *
     * @param createTime the value for tb_user_product_map.create_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_product_map.point
     *
     * @return the value of tb_user_product_map.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_product_map.point
     *
     * @param point the value for tb_user_product_map.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    public OwnerDO getUser() {
        return user;
    }

    public void setUser(OwnerDO user) {
        this.user = user;
    }

    public ProductDO getProduct() {
        return product;
    }

    public void setProduct(ProductDO product) {
        this.product = product;
    }

    public ShopDO getShop() {
        return shop;
    }

    public void setShop(ShopDO shop) {
        this.shop = shop;
    }

    public OwnerDO getOperator() {
        return operator;
    }

    public void setOperator(OwnerDO operator) {
        this.operator = operator;
    }

    @Override
    public String toString() {
        return "UserProductMapDO{" +
                "userProductId=" + userProductId +
                ", createTime=" + createTime +
                ", point=" + point +
                ", user=" + user +
                ", product=" + product +
                ", shop=" + shop +
                ", operator=" + operator +
                '}';
    }
}