package com.echo.dataobject;

import java.util.Date;

public class UserAwardMapDO {

    private Integer userAwardId;

    //顾客的信息
    private OwnerDO user;
    //private Integer userId;


    //奖品的信息
    private AwardDO award;
    //  private Integer awardId;

    //shop信息
    private ShopDO shop;
    //private Integer shopId;

    //操作员的信息
    private OwnerDO operator;

    private Date createTime;

    //奖品的可用状态
    private Integer usedStatus;

    private Integer point;

    public OwnerDO getUser() {
        return user;
    }

    public void setUser(OwnerDO user) {
        this.user = user;
    }

    public AwardDO getAward() {
        return award;
    }

    public void setAward(AwardDO award) {
        this.award = award;
    }

    public ShopDO getShop() {
        return shop;
    }

    public void setShop(ShopDO shop) {
        this.shop = shop;
    }

    public OwnerDO getOperator() {
        return operator;
    }

    public void setOperator(OwnerDO operator) {
        this.operator = operator;
    }

    public Integer getUserAwardId() {
        return userAwardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.user_award_id
     *
     * @param userAwardId the value for tb_user_award_map.user_award_id
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setUserAwardId(Integer userAwardId) {
        this.userAwardId = userAwardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.create_time
     *
     * @return the value of tb_user_award_map.create_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.create_time
     *
     * @param createTime the value for tb_user_award_map.create_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.used_status
     *
     * @return the value of tb_user_award_map.used_status
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getUsedStatus() {
        return usedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.used_status
     *
     * @param usedStatus the value for tb_user_award_map.used_status
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setUsedStatus(Integer usedStatus) {
        this.usedStatus = usedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_award_map.point
     *
     * @return the value of tb_user_award_map.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_award_map.point
     *
     * @param point the value for tb_user_award_map.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    @Override
    public String toString() {
        return "UserAwardMapDO{" +
                "userAwardId=" + userAwardId +
                ", user=" + user +
                ", award=" + award +
                ", shop=" + shop +
                ", operator=" + operator +
                ", createTime=" + createTime +
                ", usedStatus=" + usedStatus +
                ", point=" + point +
                '}';
    }
}