package com.echo.dataobject;

import java.util.Date;

public class UserShopMapDO {

    private Integer userShopId;
    private Date createTime;
    private Integer point;
    //顾客信息
    private OwnerDO user;
    //店铺信息
    private ShopDO shop;
    //private Integer shopId;

    //private String shopName;


    public Integer getUserShopId() {
        return userShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_shop_map.user_shop_id
     *
     * @param userShopId the value for tb_user_shop_map.user_shop_id
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setUserShopId(Integer userShopId) {
        this.userShopId = userShopId;
    }

    public OwnerDO getUser() {
        return user;
    }

    public void setUser(OwnerDO user) {
        this.user = user;
    }

    public ShopDO getShop() {
        return shop;
    }

    public void setShop(ShopDO shop) {
        this.shop = shop;
    }

    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_shop_map.create_time
     *
     * @param createTime the value for tb_user_shop_map.create_time
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_shop_map.point
     *
     * @return the value of tb_user_shop_map.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_shop_map.point
     *
     * @param point the value for tb_user_shop_map.point
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    @Override
    public String toString() {
        return "UserShopMapDO{" +
                "userShopId=" + userShopId +
                ", createTime=" + createTime +
                ", point=" + point +
                ", user=" + user +
                ", shop=" + shop +
                '}';
    }
}