package com.echo.dataobject;

import java.util.Date;

public class WechatAuthDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechatauth.wechat_auth_id
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    private Integer wechatAuthId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechatauth.user_id
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechatauth.open_id
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechatauth.create_time
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    private Date createTime;

    private OwnerDO personInfo;

    public OwnerDO getPersonInfo() {
        return personInfo;
    }

    public void setPersonInfo(OwnerDO personInfo) {
        this.personInfo = personInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechatauth.wechat_auth_id
     *
     * @return the value of tb_wechatauth.wechat_auth_id
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public Integer getWechatAuthId() {
        return wechatAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechatauth.wechat_auth_id
     *
     * @param wechatAuthId the value for tb_wechatauth.wechat_auth_id
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public void setWechatAuthId(Integer wechatAuthId) {
        this.wechatAuthId = wechatAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechatauth.user_id
     *
     * @return the value of tb_wechatauth.user_id
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechatauth.user_id
     *
     * @param userId the value for tb_wechatauth.user_id
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechatauth.open_id
     *
     * @return the value of tb_wechatauth.open_id
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechatauth.open_id
     *
     * @param openId the value for tb_wechatauth.open_id
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechatauth.create_time
     *
     * @return the value of tb_wechatauth.create_time
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechatauth.create_time
     *
     * @param createTime the value for tb_wechatauth.create_time
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "WechatAuthDO{" +
                "wechatAuthId=" + wechatAuthId +
                ", userId=" + userId +
                ", openId='" + openId + '\'' +
                ", createTime=" + createTime +
                ", personInfo=" + personInfo +
                '}';
    }
}