package com.echo.dao;

import com.echo.dataobject.AwardDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AwardDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_award
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int deleteByPrimaryKey(Integer awardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_award
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int insert(AwardDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_award
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int updateByPrimaryKey(AwardDO record);


    //分页查询奖品信息
    List<AwardDO> queryAwardList(@Param("awardCondition") AwardDO awardCondition,
                                 @Param("rowIndex") Integer rowIndex, @Param("pageSize") Integer pageSize);

    //查询奖品数
    int queryAwardCount(@Param("awardCondition") AwardDO awardCondition);

    AwardDO selectByPrimaryKey(Integer awardId);

    int insertSelective(AwardDO record);

    int updateByPrimaryKeySelective(AwardDO record);

    //删除某个店铺下面的某个奖品
    int deleteAward(@Param("awardId") Integer awardId, @Param("shopId") Integer shopId);

}