package com.echo.dao;

import com.echo.dataobject.HeadLineDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HeadLineDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_headline
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_headline
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insert(HeadLineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_headline
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insertSelective(HeadLineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_headline
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    HeadLineDO selectByPrimaryKey(Integer lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_headline
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(HeadLineDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_headline
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKey(HeadLineDO record);

    List<HeadLineDO> selectHeadLineList(Integer enableStatus);

}