package com.echo.dao;

import com.echo.dataobject.LocalAuthDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;


@Repository
public interface LocalAuthDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer localAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insert(LocalAuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    LocalAuthDO selectByPrimaryKey(Integer localAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(LocalAuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_auth
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */

    //更新
    int updateByPrimaryKey(LocalAuthDO record);

    //注册用户
    int insertSelective(LocalAuthDO record);

    //根据username和password进行查询
    LocalAuthDO selectByNamePwd(@Param("username") String username, @Param("password") String password);

    //根据userid进行查询
    LocalAuthDO selectByUserId(@Param("userId") Integer userId);

    //密码的修改
    int updateBypwd(@Param("userName") String userName, @Param("userId") Integer userId,
                    @Param("password") String password, @Param("newPassword") String newPassword, @Param("lastEditTime") Date lastEditTime);


}