package com.echo.dao;

import com.echo.dataobject.OwnerDO;
import org.springframework.stereotype.Repository;


@Repository
public interface OwnerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personinfo
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personinfo
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int insert(OwnerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personinfo
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int insertSelective(OwnerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personinfo
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    OwnerDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personinfo
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int updateByPrimaryKeySelective(OwnerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_personinfo
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int updateByPrimaryKey(OwnerDO record);
}