package com.echo.dao;

import com.echo.dataobject.ProductDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insert(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insertSelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    ProductDO selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKey(ProductDO record);

    //查询商品列表并分页，查寻的条件：商品名(模糊查询)，店铺id,商品类别，商品的状态
    List<ProductDO> getProductList(@Param("productCondition") ProductDO productCondition, @Param("rowIndex") Integer
            rowIndex, @Param("pageSize") Integer pageSize);

    //查询对应商品的总数
    int queryProductCount(@Param("productCondition") ProductDO productCondition);

    //更新tb_product中的productCategoryId的值为null在删除productCategory时
    int updateCategoryToNull(Integer productCategoryId);

}