package com.echo.dao;

import com.echo.dataobject.ProductImgDO;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface ProductImgDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer productImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insert(ProductImgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insertSelective(ProductImgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    ProductImgDO selectByPrimaryKey(Integer productImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(ProductImgDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_img
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKey(ProductImgDO record);

    //批量添加图片
    int batchIndertProductimg(List<ProductImgDO> productImgDOList);

    //通过productId删除商品图片
    int deleteProductImgByProductId(Integer productId);

    //根绝productId获取图片的列表
    List<ProductImgDO> queryProductImgs(Integer productId);
}