package com.echo.dao;

import com.echo.dataobject.ProductCategoryDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface ProductCategoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insert(ProductCategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insertSelective(ProductCategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    ProductCategoryDO selectByPrimaryKey(Integer productCategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(ProductCategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_product_category
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKey(ProductCategoryDO record);

    //根据shopId放回商品列表
    List<ProductCategoryDO> queryProductCategoryList(Integer shopId);

    //批量插入商品信息
    int batchInsertProductCategory(List<ProductCategoryDO> productCategoryList);

    //删除商品分类的信息 保障不会被误删，指定shopId进行删除
    int deleteProductCategory(@Param("productCategoryId") Integer productCategoryId, @Param("shopId") Integer shopId);
}