package com.echo.dao;

import com.echo.dataobject.ShopDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ShopDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int deleteByPrimaryKey(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insert(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int insertSelective(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    ShopDO selectById(Integer shopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKeySelective(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_shop
     *
     * @mbg.generated Thu Dec 26 18:10:11 CST 2019
     */
    int updateByPrimaryKey(ShopDO record);

    /**
     * 分页显示店铺
     */
    List<ShopDO> queryShopList(@Param("shopCondition") ShopDO shopCondition,
                               @Param("rowIndex") int rowIndex, @Param("pageSize") int pageSize);

    /**
     * 店铺的总数
     */

    int shopCount(@Param("shopCondition") ShopDO shopCondition);

    List<ShopDO> queryShopListByShopCategory(Integer shopCategoryId);

    /**
     * 管理员查看所有的商铺信息
     */
    List<ShopDO> getShopList(@Param("rowIndex") Integer rowIndex, @Param("pageSize") Integer pageSize);

    /**
     * 修改shop的状态
     */
    int modifyShopStatus(ShopDO shopDO);

}