package com.echo.dao;

import com.echo.dataobject.UserProductMapDO;
import org.apache.ibatis.annotations.Param;
import org.apache.logging.log4j.util.PerformanceSensitive;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface UserProductMapDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int deleteByPrimaryKey(Integer userProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int insert(UserProductMapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int insertSelective(UserProductMapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    UserProductMapDO selectByPrimaryKey(Integer userProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int updateByPrimaryKeySelective(UserProductMapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_product_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int updateByPrimaryKey(UserProductMapDO record);

    //根据查询条件分页返回信息
    List<UserProductMapDO> queryUserProductList(@Param("userProductCondition") UserProductMapDO userProductCondition
            , @Param("rowIndex") Integer rowIndex, @Param("pageSize") Integer pageSize);

    //配合查询条件的分页 返回再相同条件下的记录数
    int queryUserProductMapCount(@Param("userProductCondition") UserProductMapDO userProductCondition);

    //用户购买商品的记录
    int insertUserProductMap(UserProductMapDO userProductMap);
}