package com.echo.dao;

import com.echo.dataobject.UserProductMapDO;
import com.echo.dataobject.UserShopMapDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface UserShopMapDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_shop_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int deleteByPrimaryKey(Integer userShopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_shop_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int insertSelective(UserShopMapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_shop_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    UserShopMapDO selectByPrimaryKey(Integer userShopId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_shop_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int updateByPrimaryKey(UserShopMapDO record);


    //分页查询

    List<UserShopMapDO> queryUserShopMapList(@Param("userShopCondition") UserShopMapDO userShopCondition,
                                             @Param("rowIndex") int rowIndex, @Param("pageSize") int pageSize);
    //配合分页查询

    int queryUserShopCount(@Param("userShopCondition") UserShopMapDO userShopCondition);

    //根据用户和shopId 查询该用户再某个店铺的积分信息

    UserShopMapDO queryUserShopMap(@Param("userId") Integer userId, @Param("shopId") Integer shopId);

    //更新某个用户的积分
    int updateUserShopMapPoint(UserShopMapDO userShopMap);

    int insertUserShopMap(UserShopMapDO userShopMap);

    int updateByPrimaryKeySelective(UserShopMapDO record);

    int insert(UserShopMapDO record);
}