package com.echo.dao;

import com.echo.dataobject.UserAwardMapDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserAwardMapDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int deleteByPrimaryKey(Integer userAwardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int insert(UserAwardMapDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_award_map
     *
     * @mbg.generated Fri Feb 28 21:57:34 CST 2020
     */
    int updateByPrimaryKey(UserAwardMapDO record);

    UserAwardMapDO selectByPrimaryKey(Integer userAwardId);

    int updateByPrimaryKeySelective(UserAwardMapDO record);

    int insertSelective(UserAwardMapDO record);


    //根据查询条件分页返回奖品记录

    List<UserAwardMapDO> queryUserAwardMapList(@Param("userAwardCondition") UserAwardMapDO
                                                       userAwardCondition, @Param("rowIndex") Integer rowIndex, @Param("pageSize") Integer pageSize);

    int queryUserAwardMapCount(@Param("userAwardCondition") UserAwardMapDO userAwardCondition);

    UserAwardMapDO queryUserAwardMapById(Integer userAwardId);

    int insertUserAwardMap(UserAwardMapDO userAwardMap);

    int updateUserAwardMap(UserAwardMapDO userAwardMapDO);
}