package com.echo.dao;

import com.echo.dataobject.WechatAuthDO;
import org.springframework.stereotype.Repository;

@Repository
public interface WechatAuthDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechatauth
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int deleteByPrimaryKey(Integer wechatAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechatauth
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int insert(WechatAuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechatauth
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int insertSelective(WechatAuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechatauth
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    WechatAuthDO selectByPrimaryKey(Integer wechatAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechatauth
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int updateByPrimaryKeySelective(WechatAuthDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechatauth
     *
     * @mbg.generated Sat Feb 15 16:43:06 CST 2020
     */
    int updateByPrimaryKey(WechatAuthDO record);

    WechatAuthDO selectByOpenid(String openId);

}